FROM carlonluca/qt-dev:5.15.8-lts-lgpl

RUN apt update && \
    apt install -y \
        python3-dev python3-distro python3-setuptools \
        autotools-dev automake autoconf autopoint \
        libtool \
        g++ \
        make cmake pkg-config \
        bison \
        flex \
        nasm \
        libxv-dev \
        libx11-dev \
        libx11-xcb-dev \
        libpulse-dev \
        gettext \
        build-essential \
        libxext-dev \
        libxi-dev \
        x11proto-record-dev \
        libxrender-dev \
        libgl1-mesa-dev \
        libxfixes-dev \
        libxdamage-dev \
        libxcomposite-dev \
        libasound2-dev \
        build-essential \
        gperf \
        wget \
        libxtst-dev \
        libxrandr-dev \
        libglu1-mesa-dev \
        libegl1-mesa-dev \
        git \
        xutils-dev \
        intltool \
        ccache \
        libssl-dev

ENV QT_ANDROID_ROOT_DIR=/opt/Qt-android-5.15.8-lts-lgpl
ENV QMAKE=/opt/Qt-android-5.15.8-lts-lgpl/bin/qmake
ENV OPENSSL_ROOT_DIR=/opt/android_openssl/ssl_1.1
WORKDIR /usr/src

RUN git clone https://gitlab.freedesktop.org/gstreamer/cerbero.git /vendor/cerbero && \
    cd /vendor/cerbero && git checkout 1.20.6 

# Replace NDK version and checksums
RUN sed -i "s|NDK_VERSION = 'r21'|NDK_VERSION = 'r18b'|" /vendor/cerbero/cerbero/bootstrap/android.py && \
    sed -i "/NDK_CHECKSUMS = {/a \    'android-ndk-r18b-linux-x86_64.zip': '4f61cbe4bbf6406aa5ef2ae871def78010eed6271af72de83f8bd0b07a9fd3fd'," /vendor/cerbero/cerbero/bootstrap/android.py && \
    sed -i "s|'android-ndk-r21-linux-x86_64.zip':.*|'android-ndk-r18b-darwin-x86_64.zip': 'dd6524c3cc91725b5c39370f6deb27d8eee056e2bb2efef0a8008b4ca6d83891',|" /vendor/cerbero/cerbero/bootstrap/android.py && \
    sed -i "s|'android-ndk-r21-darwin-x86_64.zip':.*|'android-ndk-r18b-windows-x86_64.zip': '601b10d8c48486338530d55785ecb87f24ee4a98adad2ee8352f72552d434362',|" /vendor/cerbero/cerbero/bootstrap/android.py && \
    sed -i "s|'android-ndk-r21-windows-x86_64.zip':.*|'android-ndk-r18b-windows-x86.zip': '205776bf1b1b8e6b624e301063b57d49fa93e3c6da0404fdf38d5795f29c4f2d',|" /vendor/cerbero/cerbero/bootstrap/android.py

RUN sed -i "s|https://dl.google.com/android/repository/android-ndk-r21-linux-x86_64.zip|https://dl.google.com/android/repository/android-ndk-r18b-linux-x86_64.zip|" /vendor/cerbero/ci/docker_android_setup.sh
RUN sed -i "s|android-ndk-21|android-ndk-18|" /vendor/cerbero/config/android.config

ENV ANDROID_NDK_ROOT=/vendor/cerbero/build/android-ndk-18

RUN cd /vendor/cerbero && ./cerbero-uninstalled -c config/cross-android-universal.cbc bootstrap
RUN cd /vendor/cerbero && ./cerbero-uninstalled -c config/cross-android-universal.cbc -v qt5 package gstreamer-1.0

ENTRYPOINT [ "" ]
